export const ADJUST_BALANCE = "ADJUST_BALANCE";
export const SET_BALANCE = "SET_BALANCE";
export const SET_ALLOWANCE = "SET_ALLOWANCE";
export const DISPERSE_ALLOWANCE = "DISPERSE_ALLOWANCE";
export const AUTO_DISPERSE = "AUTO_DISPERSE";